config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {registrations: 'users/registrations'}

  	post '/maps/ajax', to: 'maps#ajax'
  	get '/maps/ajax', to: 'maps#ajax'

	root 'maps#index'
	resources :users
	resources :maps do
		collection do
			get :Search
		end
	end
	resources :comments
  	get 'homes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :map
	has_many :pictures, dependent: :destroy
	accepts_nested_attributes_for :pictures
end

app/controllers/comments_controller.rb
require 'kconv'
require 'aws-sdk-v1'
require 'RMagick'#require sudo yum install ImageMagick ImageMagick-devel -y

class CommentsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_comment_id, only: [:show, :edit, :update, :destroy]
  AWS.config(access_key_id: ENV["ACCESS_KEY_ID"], secret_access_key: ENV["SECRET_ACCESS_KEY"], region: 'ap-northeast-1')

  def show
    @up_result = session[:up_result]
    session[:up_result] = nil
  end

  def new
    #既にその地点にコメントをしていたらeditに飛ぶようにする
    if 0 < Comment.where('user_id = ? AND map_id = ?', current_user.id, session[:mapid]).count
      @comment = Comment.where('user_id = ? AND map_id = ?', current_user.id, session[:mapid]).first
      redirect_to comment_path(@comment) and return
    end

  	@comment = Comment.new
    @comment.pictures.build
    #session[:comment_id] = @comment.id
  	@mapid = session[:mapid]
  end

  def create
    #既にその地点にコメントをしていたらeditに飛ぶようにする
    if 0 < Comment.where('user_id = ? AND map_id = ?', current_user.id, session[:mapid]).count
      @comment = Comment.where('user_id = ? AND map_id = ?', current_user.id, session[:mapid]).first
      redirect_to comment_path(@comment) and return
    end

  	@comment = Comment.new(comment_params)
  	@comment.user_id = current_user.id
    @map = Map.find(comment_params[:map_id])
    @up_result = {}

  	if @comment.save
      if Rails.env == 'production'
        picture_up_production
      else
        picture_up_develop
      end
      @map.rank_av = Comment.where('map_id = ?', comment_params[:map_id]).average(:star_rank_score).to_f
      @map.save
      
      session[:up_result] = @up_result
  		redirect_to map_path(comment_params[:map_id]) and return
  	else
  		render 'new' and return
  	end
  end

  def edit
  end

  def update
    @map = Map.find(@comment.map_id)
    @up_result = {}

    if @comment.update(comment_params)
      if Rails.env == 'production'
        picture_up_production
      else
        picture_up_develop
      end
      @map.rank_av = Comment.where('map_id = ?', @comment.map_id).average(:star_rank_score).to_f
      @map.save

      session[:up_result] = @up_result
      redirect_to comment_path params[:id] and return
    else
      render 'new' and return
    end
  end

  def destroy
    if @comment.user_id == current_user.id
      if Rails.env == 'production'
        @comment.pictures.each do |picture|
          s3 = AWS::S3.new
          s3.buckets[ENV["AWS_S3_BUCKET"]].objects["images/"+picture.id.to_s+File.extname("#{ picture.picture_name }").downcase].delete
        end
      end
      @comment.destroy
      redirect_to map_path(session[:mapid])
    end
  end

  private
  	def comment_params
  		params.require(:comment).permit(:user_id, :map_id, :title, :text, :star_rank_score)
  	end

    def set_comment_id
      @comment = Comment.find params[:id]
    end

    def picture_up_production
      name = 'string'

      s3 = AWS::S3.new
      bucket = s3.buckets[ENV["AWS_S3_BUCKET"]]

      unless params[:comment][:picture_file].nil?
        params[:comment][:picture_file].each do |value|
          file = value
          name = file.original_filename 
          ext = name[name.rindex('.') + 1, 4].downcase

          perms = ['.jpg', '.jpeg', '.gif', '.png']
          if !perms.include?(File.extname(name).downcase)
            @up_result[name.to_s] = 'アップロードできるのは画像ファイルのみです。'
          elsif file.size > 10.megabyte
            @up_result[name.to_s] = 'ファイルサイズは10MBまでです。'
          else
            name = name.kconv(Kconv::SJIS, Kconv::UTF8)
            @picture = Picture.new
            @picture.picture_name = name
            @picture.comment_id = @comment.id
            @picture.picture_path = ENV["AWS_PICTURE_PATH"]+@picture.id.to_s
            @picture.save

            file_full_path="images/"+@picture.id.to_s+File.extname(name).downcase
            object = bucket.objects[file_full_path]
            object.write(file ,:acl => :public_read)

            original = Magick::Image.from_blob(File.read(file.tempfile)).shift
            minpic = original.resize_to_fit(250, 250)
            #minpic.write(bucket.objects[file_full_path])
            file_full_path="images/"+@picture.id.to_s+"min"+File.extname(name).downcase
            object = bucket.objects[file_full_path]
            object.write(minpic.to_blob ,:acl => :public_read)

            @up_result[name.to_s] = '画像をアップロードしました。'
          end
        end
      end
    end

    def picture_up_develop
      name = 'string'
      unless params[:comment][:picture_file].nil?
        params[:comment][:picture_file].each do |value|
          file = value
          name = file.original_filename 
          ext = name[name.rindex('.') + 1, 4].downcase
          perms = ['.jpg', '.jpeg', '.gif', '.png']
          if !perms.include?(File.extname(name).downcase)
            @up_result[name.to_s] = 'アップロードできるのは画像ファイルのみです。'
          elsif file.size > 10.megabyte
            @up_result[name.to_s] = 'ファイルサイズは10MBまでです。'
          else
            name = name.kconv(Kconv::SJIS, Kconv::UTF8)
            @picture = Picture.new
            @picture.picture_name = value.original_filename
            @picture.comment_id = @comment.id
            @picture.save
            File.open("public/docs/#{@picture.id}"+File.extname(name).downcase, 'wb') { |f| f.write(file.read) }

            original = Magick::Image.from_blob(File.read(file.tempfile)).shift
            minpic = original.resize_to_fit(250, 250)
            minpic.write("public/docs/#{@picture.id}min"+File.extname(name).downcase)
            @up_result[name.to_s] = '画像をアップロードしました。'
          end
        end
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
	<div class="field">
		<%= f.label :title, class: 'control-label' %>
		<%= f.text_field :title, id: :comment_form_title, class: 'form-control' %>
	</div>

	<div class="field">
		<%= f.label :text, class: 'control-label' %>
		<%= f.text_area :text, id: :comment_form_text, class: 'form-control'  %>
	</div>

	<label class="control-label">画像ファイルを指定:<%= f.file_field :picture_file, class: 'form-control', size: 50, multiple: true %></label><br>

	<% if type == 'new' %>
		
		<%= f.hidden_field :map_id, value: @mapid %>
	<% else %>
		<% if Rails.env == 'production' %>
			<% @comment.pictures.each do |picture| %>
				<%= image_tag "http://s3-ap-northeast-1.amazonaws.com/gatsunoko.loburd.com/images/#{picture.id}min"+File.extname("#{ picture.picture_name }").downcase %>
			<% end -%>
		<% else %>
			<% @comment.pictures.each do |picture| %>
				<%= image_tag "/docs/#{ picture.id }min"+File.extname("#{ picture.picture_name }").downcase %>
			<% end -%>
		<% end -%>
	<% end -%>


	<script type="text/javascript">
	$(function(){
	$('#star_rank').raty({
	  half     : false,
	  size     : 24,
	  score    : '<%= @comment.star_rank_score %>',
	  starHalf : '<%= asset_path('star-half.png') %>',
	  starOff  : '<%= asset_path('star-off.png') %>',
	  starOn   : '<%= asset_path('star-on.png') %>',
	  target    : '#hint',
	  targetType: 'number',
	  targetKeep: true,
	click: function(score, evt) {
	  $("#star_rank_score").val(score);
	}
	});
	});
	</script>
	<div id="star_rank"></div><div id="hint"></div>
	<%= f.hidden_field :star_rank_score, id: :star_rank_score %>

	<div class="field">
		<%= f.submit %>
	</div>
<% end -%>

app/views/comments/edit.html.erb
<h1>コメント編集</h1>
<%= render 'form', type: 'edit' %>

app/views/comments/new.html.erb
<h1>新規コメント作成</h1>
<%= render 'form', type: 'new' %>

app/views/comments/show.html.erb
<div class="col-sm-8">
<div id="comment_body">
<% unless @up_result.nil? %>
  <% @up_result.each do |key,value| %>
    <p><%= key %>: <%= value %></p>
  <% end -%>
<% end -%>

<p id="comment_show_title"><strong><%= @comment.title %></strong></p>

<% unless @comment.star_rank_score.nil? %>
  <% 5.times do |i| %>
    <% if @comment.star_rank_score >= i+1  %>
      <%= image_tag 'star-on.png' %>
    <% else %>
      <%= image_tag 'star-off.png' %>
    <% end -%>
  <% end -%>
<% end -%>

<%= simple_format(@comment.text, class: :comment_show_text) %>

<br>

<% if Rails.env == 'production' %>
  <div class="row">
    <% @comment.pictures.each do |picture| %>
      <%= link_to image_tag("http://s3-ap-northeast-1.amazonaws.com/gatsunoko.loburd.com/images/#{picture.id}min"+File.extname("#{ picture.picture_name }").downcase,
                               :class => 'comment_show_pics col-xs-6 col-sm-4'),
                           "http://s3-ap-northeast-1.amazonaws.com/gatsunoko.loburd.com/images/#{picture.id}"+File.extname("#{ picture.picture_name }").downcase,
                           :'data-lity' => "data-lity"  %>
    <% end -%>
  </div>
<% else %>
  <div class="row">
    <% @comment.pictures.each do |picture| %>
        <%= link_to image_tag("/docs/#{ picture.id }min"+File.extname("#{ picture.picture_name }").downcase,
                                :class => 'comment_show_pics col-xs-6 col-sm-4'),
                              "/docs/#{ picture.id }"+File.extname("#{ picture.picture_name }").downcase,
                              :'data-lity' => "data-lity" %>
    <% end -%>
  </div>
<% end -%>
</div><%#comment_body%>

<% unless current_user.nil? %>
  <% if @comment.user_id == current_user.id %>
    <%= link_to '編集する', edit_comment_path(@comment) %>
    <%= link_to '削除する', comment_path(@comment), method: :delete, data: { confirm: '削除してもいいですか？' } %>
  <% end -%>
<% end -%>
<br>
<%= link_to 'スポットページへ戻る', map_path(@comment.map_id) %>
</div>