config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {registrations: 'users/registrations'}

  	post '/maps/ajax', to: 'maps#ajax'
  	get '/maps/ajax', to: 'maps#ajax'

	root 'maps#index'
	resources :users
	resources :maps do
		collection do
			get :Search
		end
	end
	resources :comments
  	get 'homes/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy

  has_many :tags, dependent: :destroy
  #accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: proc { |attributes| attributes['tag_name'].blank? }

  validates :title, presence: { message: 'タイトルは必須です'}
  validates :address, presence: { message: 'だいたいの住所は必須です'}

  Geocoder.configure(language: :ja)

  # if :latitude.blank? || :longitude.blank?
  #   geocoded_by :address
  #   after_validation :geocode
  # else
  #   reverse_geocoded_by :latitude, :longitude
  #   after_validation :reverse_geocode
  # end

  geocoded_by :address, if: ->(obj){ obj.latitude.blank? or obj.longitude.blank? }
  reverse_geocoded_by :latitude, :longitude, if: ->(obj){ not (obj.latitude.blank? or obj.longitude.blank?) }
  
  after_validation :geocode, if: ->(obj){ obj.latitude.blank? or obj.longitude.blank? }
  after_validation :reverse_geocode, if: ->(obj){ not (obj.latitude.blank? or obj.longitude.blank?) }
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:edit, :update, :destroy]
  before_action :set_marker, only: [:edit]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    set_map_index(false, 35.170915, 136.8815369, "", "")
  end

  def ajax
    set_map_index(true, params[:lat], params[:lng], params[:name_search_params], params[:tag_search_params])
  end

  def show
    @map = Map.includes(:comments).order('comments.id desc').find(params[:id])
    set_marker
    session[:mapid] = @map.id
  end

  def edit
    #@map_tags = Map_tag.where('map_id = ? AND map_mster = ?', @map.id, true)
    unless @map.user_id == current_user.id
      redirect_to map_path(@map)
    end
    tagcount = Tag.where('map_id = ? AND tag_master = ?', @map.id, true).count
    tagcount = 3 - tagcount
    tagcount.times{ @map.tags.build }
  end

  def new
    if current_user.user_level > 1
      @map = Map.new
      3.times{ @map.tags.build }
    else
      redirect_to maps_path
    end
  end

  def create
    unless current_user.user_level > 1
      redirect_to maps_path
    end

    @map = Map.new(map_params)
    @map.user_id = current_user.id
    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #raise.params.inspect
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.user_level > 1 && @map.user_id == current_user.id
      @map.destroy
      redirect_to maps_path
    end
  end

  private
    def set_map
      @map = Map.find(params[:id])
    end

    def set_map_index(ajax_Judg, m_lat, m_lng, nameSearchParams, tagSearchParams)
      if (ajax_Judg)
        sp = nameSearchParams.gsub("　"," ")#全角スペースを半角スペースに変換
        sp2 = sp.gsub(" ","%,%")#半角スペースをカンマに変換(プレスホルダーの第二引数以降に使用する変数sp2に代入)
        sp2 = '%'+sp2+'%'
        sp2 = sp2.split(",")#ひとつの文字列だったsp2をカンマで区切って配列にする
        ph_title = "title like ?"
        sp.count(" ").times{
          ph_title += " AND title like ?"
        }

        unless tagSearchParams.blank?
          tg = tagSearchParams.gsub("　"," ")
          tg2 = tg.gsub(" ","%,%")
          tg2 = '%'+tg2+'%'
          tg2 = tg2.split(",")
          ph_tag = "tags.tag_name like ?"
          tg.count(" ").times{
            ph_tag += " OR tags.tag_name like ?"
          }

          @maps = Map.includes(:tags)
                      .where("latitude > ? AND latitude < ? AND longitude > ? AND longitude < ? AND ((#{ph_title}) AND (#{ph_tag}))",
                             params[:lower_lat],
                             params[:upper_lat],
                             params[:lower_lng],
                             params[:upper_lng],
                             *sp2,*tg2).order(rank_av: :desc).references(:tags)#引数に配列を渡す時に先頭に*をつけると展開されて要素の数だけ引数の数も増えて渡される
        else
          @maps = Map.includes(:tags)
                      .where("latitude > ? AND latitude < ? AND longitude > ? AND longitude < ? AND #{ph_title}",
                             params[:lower_lat],
                             params[:upper_lat],
                             params[:lower_lng],
                             params[:upper_lng],
                             *sp2).order(rank_av: :desc).references(:tags)#引数に配列を渡す時に先頭に*をつけると展開されて要素の数だけ引数の数も増えて渡される
        end
      else
        @maps = Map.all
      end
      @hash = Gmaps4rails.build_markers(@maps) do |map, marker|
        marker.lat map.latitude
        marker.lng map.longitude
        #dis = distance(map.latitude, map.longitude, m_lat, m_lng)#特定の場所からの距離を計算する関数
        marker.infowindow render_to_string(:partial => "/maps/my_template", :locals => { :object => map})
        #marker.json({title: map.title, c_distance: dis, rank_av: map.rank_av, map_id: map.id})
        marker.json({title: map.title, rank_av: map.rank_av, map_id: map.id})
        
        unless map.rank_av.nil?
          if map.rank_av >= 4
            marker.picture({
              url: ActionController::Base.helpers.asset_path('gold'),
              width: "26",
              height: "26"
            })
          elsif map.rank_av >= 2
            marker.picture({
              url: ActionController::Base.helpers.asset_path('silver'),
              width: "26",
              height: "26"
            })
          else
            marker.picture({
              url: ActionController::Base.helpers.asset_path('bronze'),
              width: "26",
              height: "26"
            })
          end
        else
          marker.picture({
            url: ActionController::Base.helpers.asset_path('bronze'),
            width: "26",
            height: "26"
          })
        end
      end
      #マーカーのハッシュを近い順にソート
      # @hash.sort! do |a, b|
      #   a[:c_distance] <=> b[:c_distance]
      # end
      #rank_av上位20件を表示するようにする
      @hash.slice!(20..-1)
      
      #近い順に表示する
      #@hashDis = @hash
      # @hashDis.sort! do |a, b|
      #   a[:c_distance] <=> b[:c_distance]
      # end
    end

    def map_params
      params.require(:map).permit(:user_id,
                                  :map_id,
                                  :title,
                                  :address,
                                  :latitude,
                                  :longitude,
                                  tags_attributes: [:id, :tag_name, :tag_master, :_destroy])
    end

  def set_marker
    @hash = Gmaps4rails.build_markers(@map) do |map, marker|
      marker.lat map.latitude
      marker.lng map.longitude
      marker.json({title: map.title})
    end
  end
  #ある場所から、別の場所への距離を計算してkmで返す
  def distance(pos1, pos2, cen1, cen2)
    Geocoder::Calculations.distance_between([pos1, pos2], [cen1, cen2]) * 1000.0
  end

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for(map) do |f| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= map.errors.count %> 個のエラーがあります</h2>
      <ul>
        <% map.errors.messages.each do |message| %>
          <li><%= message[1][0] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <%= f.fields_for :tags do |sf| %>
    <div class="field">
      <%= sf.label :tag_name, 'ユーザーによる変更禁止のタグ: ' %>
      <%= sf.text_field :tag_name %>
      <%= sf.hidden_field :tag_master, value: true %>
      <%= sf.check_box :_destroy, tabindex: -1 %>
      <%= sf.label :_destroy,"削除" %><br>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/_gmap_display.html.erb
<script>
function gmap(markers, user, {draggable = false}){
  var mapOptions = {
    mapTypeControl: google.maps.mapTypeControl = false,
    streetViewControl: google.maps.streetViewControl = false,
    draggable: draggable,
    scrollwheel: draggable
  };
  handler = Gmaps.build('Google');
  handler.buildMap({provider: mapOptions, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(markers, {draggable: draggable});
    handler.getMap().setZoom(15);
    handler.getMap().setCenter(new google.maps.LatLng(user.latitude, user.longitude));
    //add markers to original json
    _.each(markers, function(json, index){
      json.marker = markers[index];
    });

    //add dragend event to markers, triggered when you drop them
    _.each(markers, function(json){
      google.maps.event.addListener(json.marker.getServiceObject(), "dragend", function(event) {
        var lat = event.latLng.lat();
        var lng = event.latLng.lng();
        //console.log('Marker with id: ' + json.id + ' dropped hat lat: ' + lat + ' and lng: ' + lng)
        document.getElementById("map_latitude").value = event.latLng.lat();
        document.getElementById("map_longitude").value = event.latLng.lng();
      });
    });
  });
}
</script>

app/views/maps/_listDisplay.html.erb
<% @hash.each do |dista| %>
  <div class="listShow">
    <%= link_to(map_path(dista[:map_id]), :target=>["_blank"]) do %>
      <p class="listLink_text"><%= dista[:title] %></p>
      <div class="listStar">
        <% unless dista[:rank_av].nil? %>
          <% 5.times do |i| %><%# 評価に応じて星を表示する %>
            <% if dista[:rank_av] >= i+1 %>
              <%= image_tag 'star-on.png' %>
            <% elsif dista[:rank_av] > i && dista[:rank_av] < i+1 %>
              <%= image_tag 'star-half.png' %>
            <% else %>
              <%= image_tag 'star-off.png' %>
            <% end -%>
          <% end -%>
        <% else %><%# 空の場合は空の星を5個表示%>
          <% 5.times do |i| %>
            <%= image_tag 'star-off.png' %>
          <% end -%>
        <% end -%>
      </div>
    <% end -%>
  </div>
<% end -%>

app/views/maps/_my_template.html.erb
<div class="map_index_markerLinks">
  <%= link_to(map_path(object), :target=>["_blank"]) do %>
    <%= object.title %><br>
    <%= (object.rank_av.to_f).round(2) %>

    <% unless object.rank_av.nil? %>
      <% 5.times do |i| %>
        <% if object.rank_av >= i+1 %>
          <%= image_tag 'star-on.png' %>
        <% elsif object.rank_av > i && object.rank_av < i+1 %>
          <%= image_tag 'star-half.png' %>
        <% else %>
          <%= image_tag 'star-off.png' %>
        <% end -%>
      <% end -%>
    <% else %><%# 空の場合は空の星を5個表示%>
      <% 5.times do |i| %>
        <%= image_tag 'star-off.png' %>
      <% end -%>
    <% end -%>
  <% end -%>
</div>

app/views/maps/ajax.js.erb
if (infoWindow == false) {
	//既存のマーカーを削除
	_.each(markers, function(marker, index) {
		handler.removeMarker(marker);
	});
	//新しいマーカーを追加
	markers = handler.addMarkers(<%=raw @hash.to_json %>);
	//マーカーにイベントを追加
	_.each(markers, function(marker, index) {
		google.maps.event.addListener(marker.serviceObject, 'click', function(event) {
			clearTimeout(timeout_id);
			infoWindow = true; 
			timeout_id = setTimeout("infoWindow = false", 1000);
		});
	});

	$('#listDisplay').html("<%= escape_javascript(render 'listDisplay') %>");
}

app/views/maps/edit.html.erb
<h1>Editing map</h1>
<% unless @map.user_id.nil? %>
	<%= @map.user.username %>くん
<% end -%>
<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

<div style='width: 800px;'>
  <div id="map" style='width :800px; height: 600px;'></div>
</div>

<%= render 'gmap_display' %>

<script>
var map = <%= raw @map.to_json %>
var markers = <%= raw @hash.to_json %>
var options = {
  draggable: true
}
gmap(markers, map, options)
</script>

app/views/maps/index.html.erb
<div id="container">

<div class="row">
  <div id="map_index_name_search_form" class="form-group col-sm-5">
    <label class="control-label hidden-xs col-sm-1" style="padding: 0; min-width: 70px;" >スポット名</label>
    <div class="col-xs-10 col-sm-8" style="padding-right: 0;">
      <input type="text" name="name" size="30" id="name_search_params" placeholder="スポット名" class="form-control" onchange="search_action(this)">
    </div>
  </div><%#map_index_search_form%>
  <div id="map_index_tag_search_form" class="form-group col-sm-5">
    <label class="control-label hidden-xs col-sm-1" style="padding: 0; min-width: 35px;" >タグ</label>
    <div class="col-xs-10 col-sm-8" style="padding-right: 0;">
      <input type="text" name="name" size="30" id="tag_search_params" placeholder="タグ" class="form-control" onchange="search_action(this)">
    </div>
    <div class="col-xs-2 col-sm-2" style="padding: 0;">
      <button class="btn btn-primary"><i class="glyphicon glyphicon glyphicon-search"></i></button>
    </div>
  </div><%#map_index_search_form%>
</div>

<div class="row">
  <div id="listDisplay" class="col-sm-3 col-sm-push-9 hidden-xs">
  </div><%#=listDisplay%>

  <div id="mapArea" class="col-sm-9 col-sm-pull-3" style="padding: 0;">
    <div id="mapDisplay">
      <div style='width: 100%; '>
        <div id="map" style='width: 100%; min-height: 600px;'></div>
      </div>

      <script type="text/javascript">
        var timeout_id = null;
        var infoWindow = false;
        var mapOptions = { mapTypeControl: google.maps.mapTypeControl = false,
                   streetViewControl: google.maps.streetViewControl = false };
          handler = Gmaps.build('Google');
          handler.buildMap({ provider: mapOptions, internal: {id: 'map'}}, function(){
            markers = handler.addMarkers(<%=raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            //handler.fitMapToBounds();
            handler.getMap().setZoom(13);
            handler.getMap().setCenter(new google.maps.LatLng(35.165068597526094, 136.89208984375));
            //var initialBounds = handler.getBounds();
            google.maps.event.addListener(handler.getMap(), "idle", function(event) {
              var center = handler.getMap().getCenter();
              var bounds = handler.getMap().getBounds();
              $.ajax({
                  url: "maps/ajax",
                  type: "get",
                  data: {lat: center.lat,
                          lng: center.lng,
                          upper_lat: bounds.getNorthEast().lat(),
                          lower_lat: bounds.getSouthWest().lat(),
                          upper_lng: bounds.getNorthEast().lng(),
                          lower_lng: bounds.getSouthWest().lng(),
                          name_search_params: document.getElementById('name_search_params').value,
                          tag_search_params: document.getElementById('tag_search_params').value
                          },
                  dataType: "script",
                  success: function(data) {
                  },
                  error: function(data) {
                  }
              });
            });
          });

        function search_action(obj) {
          var center = handler.getMap().getCenter();
          var bounds = handler.getMap().getBounds();
          $.ajax({
              url: "maps/ajax",
              type: "get",
              data: {lat: center.lat,
                      lng: center.lng,
                      upper_lat: bounds.getNorthEast().lat(),
                      lower_lat: bounds.getSouthWest().lat(),
                      upper_lng: bounds.getNorthEast().lng(),
                      lower_lng: bounds.getSouthWest().lng(),
                      name_search_params: document.getElementById('name_search_params').value,
                      tag_search_params: document.getElementById('tag_search_params').value
                      },
              dataType: "script",
              success: function(data) {
              },
              error: function(data) {
              }
          });
        }
      </script>
    </div><%#mapDisplay%>
    <% unless current_user.nil? %>
      <% if current_user.user_level > 1 %>
        <%= link_to(new_map_path) do %>
          <div id="newMapCreate">
            <P id="map_index_newMap_">新しいマップを登録</P>
          </div>
        <% end -%>
      <% end -%>
    <% end -%>
  </div><%#mapArea%>
</div><%# row %>
</div><%#=container%>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<div id="map_show_content" class="col-sm-8">

<p id="notice"><%#= notice %></p>
<% unless @map.user_id.nil? %>
  <strong><%= @map.user.username %></strong>さんが登録した場所
<% end -%>
<p>
  <strong>スポット名:</strong>
  <%= @map.title %>
</p>
<p>
  <strong>タグ:</strong>
  <% @map.tags.each do |tag| %>
    #<%= tag.tag_name %>, 
  <% end -%>
</p>

<div id="map_show_listStar">
  <% unless @map.rank_av.nil? %>
    <% 5.times do |i| %><%# 評価に応じて星を表示する %>
      <% if @map.rank_av >= i+1 %>
        <%= image_tag 'star-on.png' %>
      <% elsif @map.rank_av > i && @map.rank_av < i+1 %>
        <%= image_tag 'star-half.png' %>
      <% else %>
        <%= image_tag 'star-off.png' %>
      <% end -%>
    <% end -%>
  <% else %><%# 空の場合は空の星を5個表示%>
    <% 5.times do |i| %>
      <%= image_tag 'star-off.png' %>
    <% end -%>
  <% end -%>
  <h4><%= @map.rank_av.to_f.round(2) %></h4>
</div>

<% unless @map.comments.nil? %>
  <div id="map_show_comments">
    <% @map.comments.each do |comment| %>
      <%= link_to(comment_path(comment)) do %>
        <div class="map_show_comment">
          <strong><%= comment.user.username %></strong>さんのコメント
          <% unless comment.star_rank_score.nil? %>
            <% 5.times do |i| %>
              <% if comment.star_rank_score >= i+1  %>
                <%= image_tag 'star-on.png' %>
              <% else %>
                <%= image_tag 'star-off.png' %>
              <% end -%>
            <% end -%>
          <% end -%>
          
          <br>
          <p class="map_comment_title"><%= comment.title %></p>
          <p class="map_comment_text"><%= truncate(comment.text, length: 100) %></p>

          <% copicCount = 0 %>
          <% if Rails.env == 'production' %>
            <div class="row">
              <% comment.pictures.each do |picture| %>
                <%= image_tag("http://s3-ap-northeast-1.amazonaws.com/gatsunoko.loburd.com/images/#{picture.id}min"+File.extname("#{ picture.picture_name }").downcase,
                    :class => 'map_show_comments_pic col-xs-6 col-sm-4') %>
                <% copicCount += 1 %>
                <% break if copicCount > 5  %>
              <% end -%>
            </div>
          <% else %>
            <div class="row">
              <% comment.pictures.each do |picture| %>
                <%= image_tag("/docs/#{ picture.id }min"+File.extname("#{ picture.picture_name }").downcase,
                    :class => 'map_show_comments_pic col-xs-6 col-sm-4') %>
                <% copicCount += 1 %>
                <% break if copicCount > 5  %>
              <% end -%>
            </div>
          <% end -%>
        </div><%# map_show_comment %>
        <% end -%>
    <% end -%>
  </div>
<% end -%>

<p>
  <strong>住所:</strong>
  <%= @map.address %>
</p>

<% unless current_user.nil? %>
  <% if @map.user_id == current_user.id %>
    <%= link_to 'Edit', edit_map_path(@map) %> |
  <% end -%>
<% end -%>
<br>
<div style='width: 100%;'>
  <div id="map" style='width :100%; height: 400px;'></div>
</div>

<%= render 'gmap_display' %>

<script>
var map = <%= raw @map.to_json %>
var markers = <%= raw @hash.to_json %>
var options = {
  draggable: false
}
gmap(markers, map, options)
</script>

<%= link_to 'コメントを書く', new_comment_path %>

<% unless current_user.nil? %>
  <% if current_user.user_level > 1 && @map.user_id == current_user.id %>
    <br><br>
    <%= link_to 'この場所を削除する', map_path(@map), method: :delete, data: { confirm: '削除してもいいですか？' } %>
  <% end -%>
<% end -%>

</div><%#map_show_body%>
<div class="col-sm-4" style="border: 1px solid blue;">
  sidebar
</div>